# Plex - IPVLAN-L2
# version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    networks:
        Antares:
          ipv4_address: 192.168.101.104
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./plex/library:/config
      - ./plex/tvseries:/tv
      - ./plex/movies:/movies
#mkdir -p plex/tvseries
#mkdir -p plex/movies
#mkdir -p plex/library
    restart: unless-stopped
networks:
  Antares:
    driver: ipvlan
    external: true