# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  query_log_file: query.log
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.18.105:9090"]
      
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - 192.168.18.108:9100

  - job_name: "cadvisor"
    static_configs:
      - targets: 
          - 192.168.18.107:8080