# Retro Arch - IPVLAN-L2
version: "3.9"

services:
  retroarch:
    image: blaize/retroarch:latest
    container_name: Retro-Arch
    ports:
      - "80:80"
    volumes:
      - /path/to/your/roms:/roms 
    restart: unless-stopped
    networks:
        Antares:
          ipv4_address: 192.168.101.102
networks:
  Antares:
    driver: ipvlan
    external: true