# EmulatorJS - IPVLAN-L2
# https://www.youtube.com/watch?v=Zv1cq0JhZfQ
# version: "2.1"

services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: Emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Lima'
      - SUBFOLDER=/ #optional
    volumes:
      - ./Configs/EmulatorJS:/config
      - ./ROMs/snes:/data/snes/roms
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001 #optional
    restart: unless-stopped
    networks:
        Antares:
          ipv4_address: 192.168.101.103
networks:
  Antares:
    driver: ipvlan
    external: true