version: '3.2'
services:
  freeradius:
    image: "freeradius/freeradius-server:latest"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      DB_HOST: mysql
      RAD_DEBUG: yes
    depends_on:
      - mysql
    networks:
        axis:
          ipv4_address: 192.168.86.10
  mysql:
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: radiussimple
      MYSQL_PASSWORD: "radpass"
      MYSQL_DATABASE: radius
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
        axis:
          ipv4_address: 192.168.87.10
networks:
  axis:
    driver: ipvlan
    external: true