version: "3.8"
services:
  website:
    image: nginx:latest
    ports:
      - "8081:80"
    restart: always
    networks:
      axis:
        ipv4_address: 192.168.94.20
networks:
  axis:
    driver: ipvlan
    external: true